// @ts-check

const foxglove = require("@foxglove/eslint-plugin");
const globals = require("globals");
const tseslint = require("typescript-eslint");

module.exports = tseslint.config(
  {
    // Generated by scripts/bundle-worker.mjs — a single bundled string, not source to lint.
    ignores: ["src/generatedWorkerSource.ts"],
  },
  {
    files: ["src/**/*.ts", "src/**/*.tsx"],
    extends: [foxglove.configs.base, foxglove.configs.react, foxglove.configs.typescript],
    languageOptions: {
      globals: {
        ...globals.es2020,
        ...globals.browser,
        ...globals.worker,
      },
      parserOptions: {
        project: "tsconfig.json",
        tsconfigRootDir: __dirname,
      },
    },
    rules: {
      "react-hooks/exhaustive-deps": "error",
    },
  },
  {
    // Co-located unit tests: adds the jest globals and the jest rule set.
    files: ["src/**/*.test.ts"],
    extends: [foxglove.configs.jest],
  },
);
